version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://localhost:5050/api
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
